### PR TITLE
more changes regarding "allow to enable basic auth by using KM_USERNAME and KM_PASSWORD as ENV VAR"

### PR DESCRIPTION
**Pull request by kevinleeTCA**
According the comments from our last PR (https://github.com/sheepkiller/kafka-manager-docker/pull/9)
We did the following small changes:
1. merge "km.sh" script to "start-kafka-manager.sh"
2. and make "start-kafka-manager.sh" as the entry point, all the auth logic are included in "start-kafka-manager.sh"

### CODE REVIEW

**Comment by sheepkiller** [comment]
Hi Kevin,

Thank you!
I'm currently in vacation with limited connectivity, I'll review it as soon as I'm back.

**Comment by kevinleeTCA** [comment]
sure, take ur time and enjoy holiday.

**Comment by sheepkiller** [comment]
Hi @kevinleeTCA,

thanks for your PR!

**Comment by kevinleeTCA** [comment]
@sheepkiller   no problems

**Pull request merged**
